jsonschema2dataclass/js2d-gradle

README.md

See https://github.com/joelittlejohn/jsonschema2pojo/issues/1070#issuecomment-650546141

Make gradle plugin to be jsonschema2pojo official plugin

---

.github/workflows/build.yml
build.gradle
src/test/groovy/com/github/eirnym/js2p/JavaTaskFunctionalTest.groovy
src/test/groovy/com/github/eirnym/js2p/JsonSchemaPluginSpec.groovy

Hi, thanks for making this Gradle plugin working and published at the Gradle plugin portal!
I wanna suggest to make it [avoiding task configuration](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) for performance, but first please check this PR which suggest introducing test enhancement. :)

Introduce test and workflow

---

.github/workflows/release.yml
build.gradle

You only set a tag and you are done.
Please see the example `git tag -a 0.2 -m "Test" && git push --tags` 
is resulting in https://github.com/hannesa2/js2p-gradle/releases/tag/0.2

Release action

---

.github/workflows/release.yml

It's a follow up of https://github.com/eirnym/js2p-gradle/issues/30#issuecomment-786453062

Publish on release

---

README.md
build.gradle
example/java/settings.gradle
settings.gradle

jsonschema2pojo -> jsonschema2dataclass renames
Fixes #43

Forgotten places to rebrand.

---

example/android/settings.gradle

It's the solution of #58 
Honestly, I don't know why, but now it's recognized well

Android include

---

src/main/groovy/com/github/eirnym/js2p/GenerateFromJsonSchemaTask.groovy
src/main/groovy/com/github/eirnym/js2p/JS2PConfig.groovy
src/main/groovy/com/github/eirnym/js2p/Js2DCExtension.java
src/main/groovy/com/github/eirnym/js2p/JsonSchema2PojoPluginConfiguration.groovy
src/main/groovy/com/github/eirnym/js2p/JsonSchemaExtension.groovy
src/main/groovy/com/github/eirnym/js2p/JsonSchemaPlugin.groovy
src/test/groovy/com/github/eirnym/js2p/JavaTaskFunctionalTest.groovy

Support multiple executions per single project

---

build.gradle
src/main/groovy/com/github/eirnym/js2p/Js2DCExtension.java
src/main/groovy/com/github/js2d/GenerateFromJsonSchemaTask.groovy
src/main/groovy/com/github/js2d/GradleRuleLogger.groovy
src/main/groovy/com/github/js2d/Js2dConfig.groovy
src/main/groovy/com/github/js2d/Js2dExtension.java
src/main/groovy/com/github/js2d/JsonSchema2dPluginConfiguration.groovy
src/main/groovy/com/github/js2d/JsonSchemaExtension.groovy
src/main/groovy/com/github/js2d/JsonSchemaPlugin.groovy
src/test/groovy/com/github/js2d/JavaTaskFunctionalTest.groovy
src/test/groovy/com/github/js2d/TestCasesGenerator.groovy
src/test/groovy/com/github/js2d/TestUtils.groovy

* package like organize name
* filename `js2d` where necessary

Naming like organization

---

README.adoc

Release batch

---

src/test/groovy/com/github/js2d/TestUtils.groovy

Test to tell we officially support Gradle 7.x

Test on Gradle 7.x

---

src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pPlugin.kt

Avoid failing when java/android plugins are not present during js2d plugin application

---

demo/android/agp4/app/build.gradle
demo/android/agp4/build.gradle
demo/android/agp7/app/build.gradle
demo/android/agp7/build.gradle

Fix compilation for agp4 and agp7 with new plugin

---

src/main/kotlin/org/jsonschema2dataclass/js2p/Js2dConfig.kt
src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pGenerationTask.kt
src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pPlugin.kt

closes  #429
@vlsi could you please test the change. If you know better solution, I'd be glad to accept it

Pass full configuration to the task

---

src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pPlugin.kt

Properly pass container properties

---

src/main/kotlin/org/jsonschema2dataclass/js2p/Js2dConfig.kt

Fix order of boolean parameters useTitleAsClassname and useJakartaValidation

---

src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pGenerationTask.kt
src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pPlugin.kt
src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pWrapperTask.kt
src/main/kotlin/org/jsonschema2dataclass/js2p/support/AndroidSupport.kt
src/main/kotlin/org/jsonschema2dataclass/js2p/support/JavaSupport.kt
src/main/kotlin/org/jsonschema2dataclass/js2p/support/android/Agp3.kt
src/main/kotlin/org/jsonschema2dataclass/js2p/support/android/Agp7.kt
src/test/kotlin/org/jsonschema2dataclass/js2p/JavaTaskFunctionalTest.kt
src/test/kotlin/org/jsonschema2dataclass/js2p/LateInitializationTest.kt
src/test/kotlin/org/jsonschema2dataclass/js2p/TestCasesGenerator.kt

This eliminates wierd issues with task registering and hooking

For Java project registers tasks as soon as possible

---

src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pPlugin.kt
src/test/kotlin/org/jsonschema2dataclass/js2p/TestUtils.kt

* Add deprecation warning when no execution defined (removed in 5.x)
* Add deprecation warning when execution property defined in the extension (will be removed in 6.x)

Add deprecation messages

---

docs/migration/migration_5.adoc

Rephrase and better explanation

5.0 migration update.

---

src/main/kotlin/org/jsonschema2dataclass/js2p/Js2dConfig.kt
src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pConfiguration.kt
src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pGenerationTask.kt
src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pPlugin.kt
src/test/kotlin/org/jsonschema2dataclass/js2p/TestCasesGenerator.kt

Reverts jsonschema2dataclass/js2d-gradle#536

Revert "Split configuration options to categories"

---

gradle/init.gradle.kts

Basic init file to build demos with current version

---

build.gradle.kts
buildSrc/build.gradle.kts
src/main/kotlin/org/jsonschema2dataclass/Js2dPlugin.kt
src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pConfig.kt
src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pGenerationTask.kt
src/main/kotlin/org/jsonschema2dataclass/support/KotlinCompat.kt

Getting ready for Gradle 8.0

---

plugin/build.gradle.kts
plugin/src/main/kotlin/org/jsonschema2dataclass/Js2dPlugin.kt
plugin/src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pConfig.kt
plugin/src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pGenerationTask.kt
plugin/src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pWorker.kt
plugin/src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pWorkerConfig.kt
plugin/src/main/kotlin/org/jsonschema2dataclass/support/AndroidSupport.kt
plugin/src/test/kotlin/org/jsonschema2dataclass/js2p/TestUtils.kt

Add an additional configuration to run processor within

---

.github/workflows/demo-android-agp7-ci-unreleased.yml
.github/workflows/demo-android-agp7-ci.yml
.github/workflows/demo-java-ci-unreleased.yml
.github/workflows/demo-java-ci.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/plugin-build-ci.yml
.github/workflows/spotless-ci.yml

https://stackoverflow.com/a/68422069/503157

Cancel previous build on update

---

plugin-gradle/commons/kotlin-compat/build.gradle.kts
plugin-gradle/commons/test-common/build.gradle.kts
plugin-gradle/compat/agp34/build.gradle.kts
plugin-gradle/compat/agp7/build.gradle.kts
plugin-gradle/compat/android/build.gradle.kts
plugin-gradle/compat/java/build.gradle.kts
plugin-gradle/processors/common/build.gradle.kts
plugin-gradle/processors/jsonschema2pojo/build.gradle.kts

See https://github.com/gradle/gradle/pull/13073 for details

Suppress gradle no valid plugin found warning

---

.github/workflows/plugin-build-ci.yml
.github/workflows/spotless-ci.yml
internal/common/src/main/kotlin/utils.kt
internal/plugins-jdk11/src/main/kotlin/org/jsonschema2dataclass/internal/plugin/SpotlessConfigPlugin.kt
internal/plugins/src/main/kotlin/org/jsonschema2dataclass/internal/plugin/base/GitVersionPlugin.kt

* Put no-git-version extra to utils
* Don't configure spotless if not enabled

Internal plugin fixes

---

gradle/init.gradle.kts
internal/plugins-jdk11/build.gradle.kts
internal/plugins/build.gradle.kts
internal/plugins/src/main/kotlin/org/jsonschema2dataclass/internal/plugin/lib/GradlePlugin.kt
internal/plugins/src/main/kotlin/org/jsonschema2dataclass/internal/plugin/lib/LibraryPlugin.kt
internal/plugins/src/main/kotlin/org/jsonschema2dataclass/internal/plugin/publishing/PublishingPlugin.kt
internal/plugins/src/main/kotlin/org/jsonschema2dataclass/internal/plugin/publishing/javadoc.kt
internal/plugins/src/main/kotlin/org/jsonschema2dataclass/internal/plugin/publishing/publishing.kt
internal/plugins/src/main/kotlin/org/jsonschema2dataclass/internal/plugin/publishing/signing.kt
plugin-gradle/common/build.gradle.kts
plugin-gradle/compat/agp34/build.gradle.kts
plugin-gradle/compat/agp7/build.gradle.kts
plugin-gradle/compat/android/build.gradle.kts
plugin-gradle/compat/java/build.gradle.kts
plugin-gradle/compat/kotlin/build.gradle.kts
plugin-gradle/processors/jsonschema2pojo/build.gradle.kts

* Set up basic publishing support
* Be able to publish to maven local folder
* Be able to run demos using version from this published folder

Basic publishing settings

---

gradle/libs.dependencies.toml

Reverts jsonschema2dataclass/js2d-gradle#749

Revert "Update dependency com.pinterest:ktlint from 0.48.2 to 0.49.0"

---

plugin-gradle/common/src/main/kotlin/org/jsonschema2dataclass/internal/task/Js2dGeneratorTaskBase.kt
plugin-gradle/plugin/src/test/kotlin/org/jsonschema2dataclass/js2p/GradleVersions.kt
plugin-gradle/plugin/src/test/kotlin/org/jsonschema2dataclass/js2p/JavaTaskFunctionalTest.kt

Fix configuration cache compatibility

---

gradle/libs.dependencies.toml
plugin-gradle/plugin/build.gradle.kts
plugin-gradle/processors/jsonschema2pojo/build.gradle.kts

* Add JUnit Platform Launcher to run JUnit5 tests   
* Specify JUnit runtime as a separate bundle

Use JUnit 5 Launcher to runtime

---

.github/workflows/renovate-verify.yml

Add workflow to verify renovate config on change

---

plugin-gradle/plugin/src/main/kotlin/org/jsonschema2dataclass/Js2dPlugin.kt
plugin-gradle/plugin/src/test/kotlin/org/jsonschema2dataclass/js2p/JavaTaskFunctionalTest.kt
plugin-gradle/plugin/src/test/kotlin/org/jsonschema2dataclass/js2p/TestUtils.kt

related to: #884 
related to: #788

Make configurations visible and re-enable configuration cache test

---

.github/workflows/plugin-build-ci.yml

Re-enable java 11 for CI
